SELECT * FROM customer;


--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customer
WHERE LOWER(discount_applied) = 'yes'
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount)::numeric, 2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::numeric 
        / COUNT(*)) * 100, 
    2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total --number of previous purchases, and show the count of each segment. 
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS total_customers,
    SUM(previous_purchases) AS total_purchases,
    ROUND(AVG(previous_purchases)::numeric, 2) AS avg_purchases
FROM customer
GROUP BY customer_segment
ORDER BY total_purchases DESC;

--Q8. What are the top 3 most purchased products within each category? 
with item_count AS (
     SELECT category, item_purchased,
	 COUNT(*) AS total_orders,
	 ROW_NUMBER() OVER (PARTITION BY category
					   ORDER BY COUNT(*) DESC) 
	 AS item_rank
	 FROM customer
     GROUP BY category, item_purchased
)

SELECT category, item_purchased, total_orders, item_rank
FROM item_count
WHERE item_rank <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status,
    COUNT(*) AS repeated_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 

SELECT age_group, 
       SUM(purchase_amount) AS Revenue
FROM customer
GROUP BY age_group
ORDER BY Revenue DESC;